spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/aviatickets
      maximum-pool-size: 20
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aviatickets
    username: development
    password: dev
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:/db.migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: public
    validate-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  google:
    maps:
      api:
        key: "AIzaSyAneQ13MFU3SQj6nOmuYBidjziLwDqOvRI"
  mail:
    host: smtp.gmail.com
    port: 587
    username: svetapiven93@gmail.com
    password: udcvpwwpbqqtnktx
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

---

airlines:
  page-capacity: 4

airports:
  page-capacity: 5

documentPass:
  page-capacity: 10

documentType:
  page-capacity: 3

flight:
  page-capacity: 5

flightStatus:
  page-capacity: 5

passenger:
  page-capacity: 10

planeType:
  page-capacity: 3

role:
  page-capacity: 2

ticket:
  page-capacity: 15

ticketClass:
  page-capacity: 3

ticketStatus:
  page-capacity: 3

user:
  page-capacity: 5

---

config:
  secret: "secret"
  expiration: 600000
  passwordSalt: cd022728-f6e1-11ed-b67e-0242ac120002

---

caffeine:
  initialCapacity: 30
  maximumSize: 1000
  expireAfterAccessDays: 1

---

