CREATE USER development WITH
LOGIN
SUPERUSER
CREATEDB
CREATEROLE
INHERIT
REPLICATION
CONNECTION LIMIT -1
PASSWORD 'dev';

CREATE DATABASE aviatickets
    WITH
    OWNER = development
ENCODING = 'UTF8'
CONNECTION LIMIT = 20;

CREATE SCHEMA public
    AUTHORIZATION development;